import TopNav from "@/app/ui/topnav";
import './globals.css';
import { ReactNode } from 'react';
import Footer from "./ui/footer";

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export const experimental_ppr = true;
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen overflow-hidden md:overflow-y-auto">
          <div className="flex flex-col">
              <TopNav/>
              <div className="flex flex-col w-full mt-10">{children}</div>
          </div>
          <div><Footer/></div>
        </div>
      </body>
    </html>
  );
}