import TopNav from "@/app/ui/shop/topnav";
import './globals.css';
import { ReactNode } from 'react';

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export const experimental_ppr = true;
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="overflow-hidden md:overflow-y-auto">
          <div className="flex flex-col h-screen">
              <TopNav/>
              <div className="flex flex-col h-screen w-full mt-10">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}